// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: nix

package base16

import (
	"fmt"
	"strings"
)

const (
	// MethodStatic is a Method of type Static.
	MethodStatic Method = 0
	// MethodDynamic is a Method of type Dynamic.
	MethodDynamic Method = 1
)

var ErrInvalidMethod = fmt.Errorf("not a valid Method, try [%s]", strings.Join(_MethodNames, ", "))

const _MethodName = "staticdynamic"

var _MethodNames = []string{
	_MethodName[0:6],
	_MethodName[6:13],
}

// MethodNames returns a list of possible string values of Method.
func MethodNames() []string {
	tmp := make([]string, len(_MethodNames))
	copy(tmp, _MethodNames)
	return tmp
}

// MethodValues returns a list of the values for Method
func MethodValues() []Method {
	return []Method{
		MethodStatic,
		MethodDynamic,
	}
}

var _MethodMap = map[Method]string{
	MethodStatic:  _MethodName[0:6],
	MethodDynamic: _MethodName[6:13],
}

// String implements the Stringer interface.
func (x Method) String() string {
	if str, ok := _MethodMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Method(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Method) IsValid() bool {
	_, ok := _MethodMap[x]
	return ok
}

var _MethodValue = map[string]Method{
	_MethodName[0:6]:  MethodStatic,
	_MethodName[6:13]: MethodDynamic,
}

// ParseMethod attempts to convert a string to a Method.
func ParseMethod(name string) (Method, error) {
	if x, ok := _MethodValue[name]; ok {
		return x, nil
	}
	return Method(0), fmt.Errorf("%s is %w", name, ErrInvalidMethod)
}

// MarshalText implements the text marshaller method.
func (x Method) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Method) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseMethod(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Method) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
