name: Go Tests

on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - "internal/**"
      - "templates/**"
      - "main.go"
      - "go.*"
  pull_request:
    branches: [main]
    paths:
      - "cmd/**"
      - "internal/**"
      - "templates/**"
      - "main.go"
      - "go.*"

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test
